# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2b58a6d34a4b211ee89dcd9ff9b3b542f729dd71cf554d57fdeba81a22083aaf8e17201af7588faefb6ce56b307d288fa918d44f7ab86c08d099110985e90b6c

test:
  secret_key_base: c48906a7df9a3ecacd213b633b9af7a1b559cfee9359bda0ebc00bc03ae16948fda6ac13da62c7fba30a517c8b57d5eb508f15462555393df5862096cbb66429

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
